name: Release Package

on: workflow_dispatch

jobs:
  build-and-upload:
    name: upload release to PyPI
    runs-on: ubuntu-latest
    environment: releaseconda
    permissions:
      #id-token: write
      contents: read
    steps:
      # https://github.com/marketplace/actions/build-conda
      - uses: actions/checkout@v3
      # Builds the package using the standard configuration
      - uses: cascode-labs/build-conda-action/action.yml@v0
        with:
          recipe_path: "recipe"
          package_artifact_name: "nbappinator"
          test_results_artifact_name: "nbappinator_testresults"
